m4b/scroll

src/ctx.rs

`StrCtx::DelimiterUntil` stopped at the end of slice when no delimiter found nor length satisfied.

Fix bug for StrCtx

---

src/endian.rs

Network byte order is big endian, not little.

Fix network byte order.

---

src/lib.rs

After `scroll_derive` is updated to use these, the 'std' dependency for `derive` can be deleted in `Cargo.toml`.

Reexport 'core' functionality for use in derives

---

src/ctx.rs

This PR adds implementations of `TryIntoCtx` and `TryFromCtx` for `&CStr` and `CString` when compiling with the `std` feature enabled. 
We could probably speed the `TryFromCtx` up a little bit by using something like `memchr` for finding the string's null terminator seeing as that's the most expensive part, but that adds an extra dependency and I wasn't sure whether it was necessary.

Serialize/Deserialize a std::ffi::CStr

---

src/ctx.rs

This change adds u128 and i128 to the list of primitive types that get
implementations of all the basic scroll traits.

Add support for u128/i128. Fixes #31.

---

src/ctx.rs

This should help in fixing https://github.com/m4b/scroll_derive/issues/15 .

Implement IntoCtx/TryIntoCtx for references to primitive types.

---

README.md

I've stumbled over this basically every time I've used scroll. :)

Mention that the derive feature needs to be enabled in the README

---

Cargo.toml
build.rs
src/ctx.rs

As discussed in https://github.com/m4b/scroll/issues/40, here's a PR which adds a build.rs that defines a rust_1_26 feature when compiled with Rust 1.26 or newer, and makes i128/u128 support conditional on that. This allows it to build with Rust 1.25.0.

Make i128/u128 support conditional on Rust 1.26.

---

README.md

This explicitly rules out enum derivation to manage user expectation

README: derive only supports struct types

---

README.md
examples/data_ctx.rs
src/ctx.rs
src/error.rs
src/leb128.rs
src/lesser.rs
src/lib.rs
src/pread.rs
src/pwrite.rs
tests/api.rs

This PR addresses https://github.com/m4b/scroll/issues/37, globally squishing `{Size,Units}` into `usize`. This is a breaking change which warrants careful consideration, but… tests pass.
Corresponding `scroll_derive` PR: https://github.com/m4b/scroll_derive/pull/19

Remove generic {Size,Units} in favor of usize

---

Cargo.toml
benches/bench.rs
build.rs
examples/data_ctx.rs
scroll_derive/Cargo.toml
scroll_derive/examples/main.rs
scroll_derive/src/lib.rs
scroll_derive/tests/tests.rs
src/ctx.rs
src/greater.rs
src/leb128.rs
src/lesser.rs
src/lib.rs
src/pread.rs
src/pwrite.rs

This PR is based on decision from #40 of @m4b : https://github.com/m4b/scroll/issues/40#issuecomment-425742488

Upgrade to 2018 edition

---

scroll_derive/src/lib.rs
scroll_derive/tests/tests.rs

Adds support for deriving `Pread`, `Pwrite`, `IOread`, `IOwrite` and `SizeWith` on structs with unnamed fields / newtypes. 
Resolves #52

Add newtype support to derive

---

scroll_derive/src/lib.rs
scroll_derive/tests/tests.rs

This adds support for deriving `Pread`, `Pwrite`, `IOread`, `IOwrite` and `SizeWith` on generic structs.

Add generics support to scroll_derive

---

src/greater.rs
src/lesser.rs
src/lib.rs

This removes the reference to the `Gread` trait (rolled into `Pread`)
and updates the links to the `FromCtx`, `IntoCtx` and `TryFromCtx`
traits.

Fix links and outdated information in doc comments

---

scroll_derive/src/lib.rs

This accommodates for an apparent change in behavior since Rust 1.47.0. When array-type struct fields are expanded in a macro, they are put in an invisible type group, which the derive needs to handle.
Minimal repro:
```rust
use scroll::Pread;
macro_rules! test {
( struct $name:ident { $( $field:ident: $t:ty, )* } ) => {
#[derive(Pread)]
pub struct $name {
$( pub $field: $t, )*
}
};
}
test! {
struct Test {
field: [u16; 40],
}
}
```

Fix derive in macro-expanded structs

---

src/ctx.rs
src/greater.rs
src/lesser.rs
src/lib.rs
src/pread.rs
src/pwrite.rs

I've recently started working with scroll and found the documentation somewhat hard to follow.
Since complaining about cool stuff I get for free (which this library definitely qualifies for) isn't all that nice I'm trying to improve the docs and structure them to be easier to follow for would-be users.
Please don't merge this PR yet; since I only just started using the library I may be wrong about some details of how stuff works; I'm mostly opening this PR to allow for easier comments and criticism on what I'm writing.
This PR will also fix #60 and fix #67 when done.

Restructuring the documentation

---

.github/workflows/main.yml
Cargo.toml

* Set minimum rust version to 1.63 due to rayon-core MSRV requirements, and add a matching `rust-version` in the Cargo.toml

Fix CI errors due to incorrect MSRV

---

.github/workflows/main.yml
src/ctx.rs
src/error.rs
src/leb128.rs
src/lib.rs
tests/api.rs

This uses MSRV fix #90
* Fix `cargo test --no-default-features` to pass by making std-only tests/docs conditional (added to CI)
* Added `Error::Custom(&'static str)` for no-std mode
There are a few `FIXME` in the code where things seemed suspicious

Add nostd tests

---

Cargo.toml
examples/data_ctx.rs
src/ctx.rs
src/endian.rs
src/error.rs
src/leb128.rs
src/lesser.rs
src/lib.rs
tests/api.rs

* Optimize/cleanup use statements
* Do not expose `scroll_derive` as a feature in Cargo.toml
* Minor clippy lints
The format args inlining was moved to #91

Minor linting, warning fixes

---

examples/data_ctx.rs
scroll_derive/README.md
scroll_derive/examples/main.rs
scroll_derive/tests/tests.rs
src/ctx.rs
src/error.rs
src/leb128.rs
src/lib.rs
tests/api.rs

This is a subset of the original #84 
Make code a bit easier to read, and also, per rust issue 112156, there is a 6% perf hit when using refs with format, so this PR also fixes that.
See https://github.com/rust-lang/rust/issues/112156

Inline format args (better perf)

---

src/lib.rs
src/pread.rs
src/pwrite.rs

Retake of #81.
It does not allow reading zero-sized types (like possibly an empty array) from empty slice
Contains documentation in the `Pread` and `Pwrite` trait, test is fixed.

Do not error out of g{read,write}_with if the offset is equal to slice len

---

src/ctx.rs
tests/api.rs

This PR makes reading and writing possible for fixed length arrays of any type implementing `TryFromCtx` or `TryIntoCtx`.

Provided RW impl for fixed arrays.

---

src/ctx.rs
tests/api.rs

This PR adds a generic implementation of `SizeWith` for a fixed size array.

Added SizeWith impl for fixed array.

---

src/ctx.rs

This PR introduces `SizeWith` impls for numeric types, without requiring `Endian` as context. It wasn't immediately clear, to me, why the ctx was required.

Added SizeWith impl for numeric types without Ctx.

---

scroll_derive/Cargo.toml
scroll_derive/src/lib.rs
scroll_derive/tests/tests.rs

scroll_derive: support reference

---

scroll_derive/examples/derive_custom_ctx.rs
scroll_derive/src/lib.rs
scroll_derive/tests/tests.rs

Add attribute to override the context in `scroll-derive` used like the following:
```rust
#[derive(Pread, Pwrite, SizeWith)]
#[repr(C)]
struct Data {
id: u32,
timestamp: f64,
#[scroll(ctx = BE)]
arr: [u16; 2],
#[scroll(ctx = CustomCtx::len())]
custom_ctx: CustomCtx,
}
```
where `ctx` doesn't have to be of type `Endian` and ignores `pread_with`'s (and related) `ctx` argument.
Use case for this includes using the derive macro for structs that don't use `Endian` as their context and deriving many `Network` Endian structs while still being able to use `pread`/`gread`/`pwrite`/`gwrite` without having to specify `Network` Endian every time.
A future extension to this can enable using previous fields in the expression which would enable a pattern like:
```rust
#[derive(Pread, Pwrite, SizeWith)] …
```

Custom ctx override for derive macro

---

scroll_derive/src/lib.rs

This causes downstream clippy warnings on #[derive(IOwrite)]:
warning: unneeded unit expression
--> src/types.rs:195:59
|
195 | #[derive(Debug, Copy, Clone, DerivePread, Pwrite, IOread, IOwrite, SizeWith)]
|                                                           ^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit
= note: this warning originates in the derive macro `IOwrite` (in Nightly builds, run with -Z macro-backtrace for more info)

Remove unneeded unit expression

---

.github/workflows/main.yml
Cargo.toml
src/error.rs

Now that `core::error::Error` is available in stable Rust (as of 1.81.0), we can close #111.

Implement core::error::Error

---

.github/workflows/main.yml
Cargo.toml
examples/data_ctx.rs
src/ctx.rs
src/endian.rs
src/error.rs
src/leb128.rs
src/lib.rs
tests/api.rs

This was discussed in #111, so I figured I'd do this too while I was at it.

Use Rust 2024, bump MSRV to 1.85

---

src/ctx.rs

As discussed, I replaced the unsafe `from_bytes_with_nul_unchecked`, with `from_bytes_until_nul` and simplified the writing.

Made `Try{From|Into}Ctx impl` on `CStr` safe.
